/*************************************************
Copyright: Baosight Software LTD.co Copyright (c) 2013
Author:
Version:     1.0
Date:        2021/8/31 13:40:05
Description: 一系列连铸生产日报
**************************************************/
/***** C/C++ 的标准头文件部分 *****/
#include "stdafx.h"

/***** 头文件部分 *****/

//#include "AppFunc.h"

/*<remark>=========================================================
/// <summary>
///  一系列生产计划查询
/// <para>
/// </para>
/// <para>数据库表：</para>
/// </summary>
/// <param name="">  </param>
/// <returns>返回参数：材料数据</returns>
===========================================================</remark>*/
// Service 入口
BM2F_ENTERACE(mmsmap09_inq)

int f_mmsmap09_inq(EIClass * bcls_rec, EIClass * bcls_ret, CDbConnection * conn)
{
	CTracer log(__FUNCTION__);

	/* 程序内部变量 */
	int doFlag = 0;

	/* 业务变量 */
	CString datetime1("");
	CString datetime2("");
	CString v_date("");
	/* 数据库SQL操作字符串 */
	CString sqlstr("");

	/* 实体类定义 */


	/* 数据库操作类定义 */
	CDbCommand cmd_inq(conn);
	//AppFunc XYZ(bcls_rec, bcls_ret, conn);

	try
	{
		//---------------------------------------------------
		//获得输入参数
		datetime1 = bcls_rec->Tables[0].Rows[0]["DATE_TIME_F"].ToString().Trim() + "210000";
		datetime2 = bcls_rec->Tables[0].Rows[0]["DATE_TIME_T"].ToString().Trim() + "210000";
		v_date = bcls_rec->Tables[0].Rows[0]["DATE_TIME_T"].ToString().Substring(0, 8);

		/* ***** 打印输入参数 ***** */
		Log::Trace("", __FUNCTION__, "====== 接收块开始datetime1[{0}],datetime2[{1}] =======  ", datetime1, datetime2);


		switch (conn->DatabaseKind)
		{
		case DB_KIND_DB2:				// DB2 数据库（未开Oracle兼容）
		case DB_KIND_DB2_ORACLE:	    // DB2 数据库（开Oracle兼容）
		case DB_KIND_MSSQL:				// MS SQL Server数据库
		case DB_KIND_ORACLE:	        // Oracle 数据库
		default:


			sqlstr = "  select *  from  (   "
				"  select mm.zjh xh,mm.zjh||'#连铸' zjh,mm.drls,mm.ljls,mm.drjzgsl,mm.ljjzgsl,mm.drgpqgl,mm.ljgpqgl,mm.drjzzzq,mm.ljjzzzq,	 "
				"  mm.drzq, mm.ljzq, mm.drdlcs, mm.ljdlcs, mm.drylcs, mm.ljylcs, mm.drzbgs, mm.ljzbgs, mm.drdzbsm, mm.ljdzbsm, mm.drxxpz, mm.ljxxpz,	 "
				"  nvl(nn.drtjsj, 0) drtjsj, case when nvl(mm.drls,0)>=1 then nvl(nn.drzjzyl, 100) else 0 end drzjzyl, "
				"  nvl(nn.ljtjsj, 0) ljtjsj, case when nvl(mm.ljls,0)>=1 then nvl(nn.ljzjzyl, 100) else 0 end ljzjzyl	 "
				"  from (	 "
				"  select zjh, sum(drls) drls, sum(ljls) ljls, sum(drjzgsl) drjzgsl, sum(ljjzgsl) ljjzgsl,	 "
				"  sum(drgpqgl) drgpqgl, sum(ljgpqgl) ljgpqgl, sum(drjzzzq) drjzzzq, sum(ljjzzzq) ljjzzzq,	 "
				"  sum(drzq) drzq, sum(ljzq) ljzq, sum(drdlcs) drdlcs, sum(ljdlcs) ljdlcs, sum(drylcs) drylcs, sum(ljylcs) ljylcs, sum(drzbgs) drzbgs, sum(ljzbgs) ljzbgs,	 "
				"  decode(sum(drzbgs), 0, 0, cast(sum(drzbls) *1.0/ sum(drzbgs) as decimal(10, 1))) drdzbsm,	 "
				"  decode(sum(ljzbgs), 0, 0, cast(sum(ljzbls) *1.0 / sum(ljzbgs) as decimal(10, 1))) ljdzbsm,	 "
				"  sum(drxxpz) drxxpz, sum(ljxxpz) ljxxpz	 "
				"  from  (	 "
				"  select substr(a.CAST_NO, 2, 1) zjh, 0 as drls, 0 as drjzgsl, 0 as drgpqgl, 0 as drjzzzq, 0 as drzq,	 "
				"  count(a.heat_no) as ljls, sum(a.CAST_STEEL_WT) as ljjzgsl, sum(b.slab_wt) as ljgpqgl,	 "
				"  sum(a.POUR_PERIOD) ljjzzzq, cast(round(cast(sum(a.POUR_PERIOD) as decimal(31, 3)) / count(a.heat_no), 2) as decimal(31, 2)) ljzq,	 "
				"  sum(decode(substr(a.cast_no, 2, 1), '5', 6 - CUTOFF_TIMES, '6', 6 - CUTOFF_TIMES, '7', 6 - CUTOFF_TIMES, 0)) drdlcs, 0 ljdlcs,	 "
				"  0 drylcs, 0 ljylcs, 0 drzbgs, 0 ljzbgs, 0 drxxpz, 0 ljxxpz, 0 drzbls,0 ljzbls 	 "
				"  from tmmsm31 a, (select heat_no, SUM(SLAB_WT) slab_wt FROM TMMSM33 group by heat_no) b	 "
				"  WHERE a.OPEN_TIME<>' ' and a.heat_no = b.heat_no	 "
				"  and a.OPEN_TIME >= @datetime1	 "
				"  and a.OPEN_TIME <  @datetime2	 "
				"  group by substr(a.CAST_NO, 2, 1)	 "
				"  union all	 "
				"  select substr(a.CAST_NO, 2, 1) zjh, count(a.heat_no) drls, sum(a.CAST_STEEL_WT) drjzgsl, sum(b.slab_wt) drgpqgl,	 "
				"  sum(a.POUR_PERIOD) drjzzzq, cast(round(cast(sum(a.POUR_PERIOD) as decimal(31, 3)) / count(a.heat_no), 2) as decimal(31, 2)) drzq,	 "
				"  0 ljls, 0 as ljjzgsl, 0 as ljgpqgl, 0 as ljjzzzq, 0 as ljzq,	 "
				"  0 drdlcs, sum(decode(substr(a.cast_no, 2, 1), '5', 6 - CUTOFF_TIMES, '6', 6 - CUTOFF_TIMES, '7', 6 - CUTOFF_TIMES, 0)) ljdlcs, 0 drylcs, 0 ljylcs,	 "
				"  0 drzbgs, 0 ljzbgs, 0 drxxpz, 0 ljxxpz	, 0 drzbls,0 ljzbls  "
				"  from tmmsm31 a, (select heat_no, SUM(SLAB_WT) slab_wt FROM TMMSM33 group by heat_no) b	 "
				"  WHERE a.OPEN_TIME<>' '	and a.heat_no = b.heat_no	 "
				"  and TO_CHAR((to_date(a.OPEN_TIME, 'YYYYMMDDHH24MISS') + 3 HOUR), 'YYYYMMDD') = @v_date	 "
				"  group by substr(a.CAST_NO, 2, 1)	 "
				"  union all	 "
				"	  select substr(t.cast_no, 2, 1) zjh,	 															"
				"					  0 drls, 0 drjzgsl, 0 drgpqgl, 0 drjzzzq, 0 drzq, 0 ljls, 0 as ljjzgsl, 0 as ljgpqgl, 0 as ljjzzzq, 0 as ljzq, 0 drdlcs, 0 ljdlcs, 0 drylcs, 0 ljylcs,	 											"
				"					  0, count(t.heat_no) ljzbgs, 0 drxxpz, 0 ljxxpz ,0 drzbls,sum(mid_heat_seq) ljzbls   from tmmsm31  t,	 											"
				"	          (select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq  from 																"
				"	                          (select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11	 															"
				"	                				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41	 											"
				"	                				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11b	 											"
				"	                				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41b	)											"
				"	          where (cast_no,mid_seq,mid_heat_seq) in 																"
				"	            				  (select cast_no,mid_seq,max(mid_heat_seq) from												"
				"	                        (select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11	 															"
				"	              				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41	 											"
				"	              				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11b	 											"
				"	              				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41b)												"
				"	                       where cast_no||lpad(mid_seq,2,0) not in 																"
				"	                       (select jcxx from (select substr(cast_no,2,1), max(cast_no||lpad(mid_seq,2,0)) jcxx from 																"
				"	                                                  (select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11	 															"
				"	                                          				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41	 											"
				"	                                          				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11b	 											"
				"	                                          				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41b)												"
				"	                                          group by substr(cast_no,2,1) )  )																"
				"	                      group by cast_no,mid_seq)   ) tp11	        															"
				"					  where t.heat_no = tp11.heat_no  												"
				"					    and close_time<>' '	 											"
				"					    and close_time>=@datetime1 												"
				"	            and close_time< @datetime2            																"
				"					 group by substr(t.cast_no, 2, 1)	 											"
				"  union all	 "
				"	 select substr(t.cast_no, 2, 1) zjh,	 														"
				"					  0 drls, 0 drjzgsl, 0 drgpqgl, 0 drjzzzq, 0 drzq, 0 ljls, 0 as ljjzgsl, 0 as ljgpqgl, 0 as ljjzzzq, 0 as ljzq, 0 drdlcs, 0 ljdlcs, 0 drylcs, 0 ljylcs,	 										"
				"					  count(t.heat_no) drzbgs, 0 ljzbgs, 0 drxxpz, 0 ljxxpz , sum(mid_heat_seq) drzbls,0 ljzbls  from tmmsm31  t,	 	 									"
				"	          (select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq  from 															"
				"	                          (select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11	 														"
				"	                				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41	 										"
				"	                				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11b	 										"
				"	                				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41b	)										"
				"	          where (cast_no,mid_seq,mid_heat_seq) in 															"
				"	            				  (select cast_no,mid_seq,max(mid_heat_seq) from											"
				"	                        (select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11	 														"
				"	              				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41	 										"
				"	              				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11b	 										"
				"	              				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41b)											"
				"	                       where cast_no||lpad(mid_seq,2,0) not in 															"
				"	                       (select jcxx from (select substr(cast_no,2,1), max(cast_no||lpad(mid_seq,2,0)) jcxx from 															"
				"	                                                  (select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11	 														"
				"	                                          				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41	 										"
				"	                                          				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11b	 										"
				"	                                          				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41b)											"
				"	                                          group by substr(cast_no,2,1) )  )															"
				"	                      group by cast_no,mid_seq)   ) tp11	        														"
				"					  where t.heat_no = tp11.heat_no  											"
				"					    and close_time<>' '	 										"
				"					    and TO_CHAR((to_date(close_time, 'YYYYMMDDHH24MISS') + 3 HOUR), 'YYYYMMDD') = @v_date	 										"
				"					 group by substr(t.cast_no, 2, 1)	 										"

				"  union all	 "
				"  select  decode(substr(mat_no, 9, 1), '1', 1, '2', 1, '3', 2, '4', 2, '5', 3,	 "
				"  'A', 5, 'B', 5, 'C', 5, 'D', 5, 'E', 5, 'F', 5,	 "
				"  'G', 6, 'H', 6, 'I', 6, 'J', 6, 'K', 6, 'L', 6,	 "
				"  'M', 7, 'N', 7, 'O', 7, 'P', 7, 'Q', 7, 'R', 7) zjh,	 "
				"  0 drls, 0 drjzgsl, 0 drgpqgl, 0 drjzzzq, 0 drzq, 0 ljls, 0 as ljjzgsl, 0 as ljgpqgl, 0 as ljjzzzq, 0 as ljzq, 0 drdlcs, 0 ljdlcs, 0 drylcs, 0 ljylcs,	 "
				"  0 drzbgs, 0 ljzbgs, decimal(SUM(MAT_WT), 20, 3) drxxpz, 0 ljxxpz, 0 drzbls,0 ljzbls	 "
				"  from twma4	 "
				"  where STOCK_OPER_ORDER = '1B' and SLAT_UNLADE_CAUSE<>' '	 and FUNC_ID='wmsmsm13_downline' "
				"  and TO_CHAR((to_date(REC_CREATE_TIME, 'YYYYMMDDHH24MISS') + 3 HOUR), 'YYYYMMDD') = @v_date	 "
				"  group by decode(substr(mat_no, 9, 1), '1', 1, '2', 1, '3', 2, '4', 2, '5', 3,	 "
				"  'A', 5, 'B', 5, 'C', 5, 'D', 5, 'E', 5, 'F', 5,	 "
				"  'G', 6, 'H', 6, 'I', 6, 'J', 6, 'K', 6, 'L', 6,	 "
				"  'M', 7, 'N', 7, 'O', 7, 'P', 7, 'Q', 7, 'R', 7)	 "
				"  union all	 "
				"  select  decode(substr(mat_no, 9, 1), '1', 1, '2', 1, '3', 2, '4', 2, '5', 3,	 "
				"  'A', 5, 'B', 5, 'C', 5, 'D', 5, 'E', 5, 'F', 5,	 "
				"   'G', 6, 'H', 6, 'I', 6, 'J', 6, 'K', 6, 'L', 6, "
				"  'M', 7, 'N', 7, 'O', 7, 'P', 7, 'Q', 7, 'R', 7) zjh,	 "
				"  0 drls, 0 drjzgsl, 0 drgpqgl, 0 drjzzzq, 0 drzq, 0 ljls, 0 as ljjzgsl, 0 as ljgpqgl, 0 as ljjzzzq, 0 as ljzq, 0 drdlcs, 0 ljdlcs, 0 drylcs, 0 ljylcs,	 "
				"  0 drzbgs, 0 ljzbgs, 0 drxxpz, decimal(SUM(MAT_WT), 20, 3) ljxxpz	, 0 drzbls,0 ljzbls "
				"  from twma4	 "
				"  where STOCK_OPER_ORDER = '1B' and SLAT_UNLADE_CAUSE<>' '	and FUNC_ID='wmsmsm13_downline'  "
				"  and REC_CREATE_TIME >= @datetime1	 "
				"  and REC_CREATE_TIME <  @datetime2	 "
				"  group by decode(substr(mat_no, 9, 1), '1', 1, '2', 1, '3', 2, '4', 2, '5', 3,	 "
				"  'A', 5, 'B', 5, 'C', 5, 'D', 5, 'E', 5, 'F', 5,	 "
				"  'G', 6, 'H', 6, 'I', 6, 'J', 6, 'K', 6, 'L', 6,	 "
				"  'M', 7, 'N', 7, 'O', 7, 'P', 7, 'Q', 7, 'R', 7)	 "
				"   union all select substr(code,2,1) ZJH,0 drls, 0 drjzgsl, 0 drgpqgl, 0 drjzzzq, 0 drzq, 0 ljls, 0 as ljjzgsl, 0 as ljgpqgl, 0 as ljjzzzq, 0 as ljzq, 0 drdlcs, 0 ljdlcs, 0 drylcs, 0 ljylcs,	    "
				"    0 drzbgs, 0 ljzbgs, 0 drxxpz, 0 ljxxpz, 0 drzbls, 0 ljzbls  from tep0002 where CODE_CLASS = 'TMNC'     "
				"  )	 "
				"  group by zjh)  mm  left join	 "
				"		( select zjh, nvl(sum(drtjsj),0) drtjsj, round(cast((1 - nvl(sum(drtjsj),0)*1.0 / 1440.00) * 100 as decimal(6, 2)), 2) drzjzyl, nvl(sum(ljtjsj),0) ljtjsj, sum(ljzjzyl) ljzjzyl from (	       																"
				"							  select zjh, nvl(sum(tjsjjg),0) drtjsj, round(cast((1 - nvl(sum(tjsjjg),0)*1.0 / 1440.00) * 100 as decimal(6, 2)), 2) drzjzyl, 0 ljtjsj, 0 ljzjzyl from (												"
				"							           select zjh,rq,sum(tjsj) tjsjjg  from (												"
				"							 select zjh,rq,sjc1 tjsj from (												"
				"							  select substr(sjc.cast_no,2,1) zjh, to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq,												"
				"							  right(digits(cast(timestampdiff(4,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),4) sjc1,												"
				"							  right(digits(cast(timestampdiff(4,(to_date(to_char((to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR),'yyyymmdd')||'240000','yyyymmddhh24miss'))-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),4) sjc2,												"
				"							  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq2,												"
				"							  right(digits(cast(timestampdiff(4,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss')) as  bigint)),4) sjc3,												"
				"							  to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR tjsj,to_date(to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'240000','yyyymmddhh24miss') tjrq1, 												"
				"							  to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR kjsj,to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss') kjrq2, 												"
				"							  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')-to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') sjc,												"
				"							  *												"
				"							  from 												"
				"							  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3') and cast_div_no = '1') xjc,      												"
				"							  					  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3')      							"
				"							  					  and(substr(cast_no, 1, 6), cast_div_no) in      							"
				"							  					  (select substr(cast_no, 1, 6), max(cast_div_no) from tmmsm31 group by substr(cast_no, 1, 6))) sjc      							"
				"							  					  where substr(xjc.cast_no,2,5) = substr(sjc.cast_no,2,5) + 1    							"
				"							              and sjc.CLOSE_TIME<>' ' and xjc.open_time<>' '												"
				"							   order by xjc.CAST_NO desc ) where sjc=0 												"
				"							 union all												"
				"							  select zjh,rq,sjc2 from (												"
				"							  select substr(sjc.cast_no,2,1) zjh, to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq,												"
				"							  right(digits(cast(timestampdiff(4,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),4) sjc1,												"
				"							  right(digits(cast(timestampdiff(4,(to_date(to_char((to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR),'yyyymmdd')||'240000','yyyymmddhh24miss'))-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),4) sjc2,												"
				"							  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq2,												"
				"							  right(digits(cast(timestampdiff(4,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss')) as  bigint)),4) sjc3,												"
				"							  to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR tjsj,to_date(to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'240000','yyyymmddhh24miss') tjrq1, 												"
				"							  to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR kjsj,to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss') kjrq2, 												"
				"							  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')-to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') sjc,												"
				"							  *												"
				"							  from 												"
				"							  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3') and cast_div_no = '1') xjc,      												"
				"							  					  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3')      							"
				"							  					  and(substr(cast_no, 1, 6), cast_div_no) in      							"
				"							  					  (select substr(cast_no, 1, 6), max(cast_div_no) from tmmsm31 group by substr(cast_no, 1, 6))) sjc      							"
				"							  					   where substr(xjc.cast_no,2,5) = substr(sjc.cast_no,2,5) + 1     							"
				"							              and sjc.CLOSE_TIME<>' ' and xjc.open_time<>' '												"
				"							   order by xjc.CAST_NO desc ) where sjc=1												"
				"							   union all												"
				"							  select zjh,rq2,sjc3 from (												"
				"							  select substr(sjc.cast_no,2,1) zjh, to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq,												"
				"							  right(digits(cast(timestampdiff(4,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),4) sjc1,												"
				"							  right(digits(cast(timestampdiff(4,(to_date(to_char((to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR),'yyyymmdd')||'240000','yyyymmddhh24miss'))-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),4) sjc2,												"
				"							  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq2,												"
				"							  right(digits(cast(timestampdiff(4,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss')) as  bigint)),4) sjc3,												"
				"							  to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR tjsj,to_date(to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'240000','yyyymmddhh24miss') tjrq1, 												"
				"							  to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR kjsj,to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss') kjrq2, 												"
				"							  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')-to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') sjc,												"
				"							  *												"
				"							  from 												"
				"							  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3') and cast_div_no = '1') xjc,      												"
				"							  					  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3')      							"
				"							  					  and(substr(cast_no, 1, 6), cast_div_no) in      							"
				"							  					  (select substr(cast_no, 1, 6), max(cast_div_no) from tmmsm31 group by substr(cast_no, 1, 6))) sjc      							"
				"							  					   where substr(xjc.cast_no,2,5) = substr(sjc.cast_no,2,5) + 1   							"
				"							              and sjc.CLOSE_TIME<>' ' and xjc.open_time<>' '												"
				"							   order by xjc.CAST_NO desc ) where sjc=1 												"
				"							   )												"
				"							   where rq=@v_date												"
				"							   group by zjh,rq												"
				"							   order by zjh desc, rq desc												"
				"							 ) group by zjh												"
				"							 												"
				"							 union all												"
				"							 												"
				"							  select zjh, 0 drtjsj, 0 drzjzyl, cast(sum(tjsjjg)/60 as decimal(20,0)) ljtjsj, cast(100 * (1 - sum(tjsjjg) / 60 *1.0 / timestampdiff(16, to_date(substr(@datetime2, 1, 8), 'yyyymmdd') - to_date(substr(@datetime1, 1, 8), 'yyyymmdd')) / 1440 ) as decimal(20, 2))  ljzjzyl from (												"
				"							           select zjh,rq,sum(tjsj) tjsjjg  from (												"
				"							 select zjh,rq,sjc1 tjsj from (												"
				"							  select substr(sjc.cast_no,2,1) zjh, to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq,												"
				"							  right(digits(cast(timestampdiff(2,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),8) sjc1,												"
				"							  right(digits(cast(timestampdiff(2,(to_date(to_char((to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR),'yyyymmdd')||'240000','yyyymmddhh24miss'))-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),8) sjc2,												"
				"							  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq2,												"
				"							  right(digits(cast(timestampdiff(2,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss')) as  bigint)),8) sjc3,												"
				"							  to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR tjsj,to_date(to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'240000','yyyymmddhh24miss') tjrq1, 												"
				"							  to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR kjsj,to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss') kjrq2, 												"
				"							  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')-to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') sjc,												"
				"							  *												"
				"							  from 												"
				"							  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3') and cast_div_no = '1') xjc,      												"
				"							  					  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3')      							"
				"							  					  and(substr(cast_no, 1, 6), cast_div_no) in      							"
				"							  					  (select substr(cast_no, 1, 6), max(cast_div_no) from tmmsm31 group by substr(cast_no, 1, 6))) sjc      							"
				"							  					    where substr(xjc.cast_no,2,5) = substr(sjc.cast_no,2,5) + 1   							"
				"							              and sjc.CLOSE_TIME<>' ' and xjc.open_time<>' '												"
				"							   order by xjc.CAST_NO desc ) where sjc=0 												"
				"							 union all												"
				"							  select zjh,rq,sjc2 from (												"
				"							  select substr(sjc.cast_no,2,1) zjh, to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq,												"
				"							  right(digits(cast(timestampdiff(2,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),8) sjc1,												"
				"							  right(digits(cast(timestampdiff(2,(to_date(to_char((to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR),'yyyymmdd')||'240000','yyyymmddhh24miss'))-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),8) sjc2,												"
				"							  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq2,												"
				"							  right(digits(cast(timestampdiff(2,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss')) as  bigint)),8) sjc3,												"
				"							  to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR tjsj,to_date(to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'240000','yyyymmddhh24miss') tjrq1, 												"
				"							  to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR kjsj,to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss') kjrq2, 												"
				"							  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')-to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') sjc,												"
				"							  *												"
				"							  from 												"
				"							  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3') and cast_div_no = '1') xjc,      												"
				"							  					  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3')      							"
				"							  					  and(substr(cast_no, 1, 6), cast_div_no) in      							"
				"							  					  (select substr(cast_no, 1, 6), max(cast_div_no) from tmmsm31 group by substr(cast_no, 1, 6))) sjc      							"
				"							  					    where substr(xjc.cast_no,2,5) = substr(sjc.cast_no,2,5) + 1   							"
				"							              and sjc.CLOSE_TIME<>' ' and xjc.open_time<>' '												"
				"							   order by xjc.CAST_NO desc ) where sjc=1												"
				"							   union all												"
				"							  select zjh,rq2,sjc3 from (												"
				"							  select substr(sjc.cast_no,2,1) zjh, to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq,												"
				"							  right(digits(cast(timestampdiff(2,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),8) sjc1,												"
				"							  right(digits(cast(timestampdiff(2,(to_date(to_char((to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR),'yyyymmdd')||'240000','yyyymmddhh24miss'))-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),8) sjc2,												"
				"							  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq2,												"
				"							  right(digits(cast(timestampdiff(2,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss')) as  bigint)),8) sjc3,												"
				"							  to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR tjsj,to_date(to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'240000','yyyymmddhh24miss') tjrq1, 												"
				"							  to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR kjsj,to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss') kjrq2, 												"
				"							  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')-to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') sjc,												"
				"							  *												"
				"							  from 												"
				"							  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3') and cast_div_no = '1') xjc,      												"
				"							  					  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3')      							"
				"							  					  and(substr(cast_no, 1, 6), cast_div_no) in      							"
				"							  					  (select substr(cast_no, 1, 6), max(cast_div_no) from tmmsm31 group by substr(cast_no, 1, 6))) sjc      							"
				"							  					    where substr(xjc.cast_no,2,5) = substr(sjc.cast_no,2,5) + 1    							"
				"							              and sjc.CLOSE_TIME<>' ' and xjc.open_time<>' '												"
				"							   order by xjc.CAST_NO desc ) where sjc=1 												"
				"							   )												"
				"							   where rq>=@datetime1												"
				"							     and rq< @datetime2												"
				"							   group by zjh,rq												"
				"							   order by zjh desc, rq desc												"
				"							 ) group by zjh												"
				"							 )  group by zjh												"
				"																			"
				"      )  nn	on  mm.zjh = nn.zjh			 "
				"  union all  "
				"  select mm.zjh xh, decode(mm.zjh, '4.1', '一系列', '8', '二系列') zjh, mm.drls, mm.ljls, mm.drjzgsl, mm.ljjzgsl, mm.drgpqgl, mm.ljgpqgl, mm.drjzzzq, mm.ljjzzzq,     "
				"  mm.drzq, mm.ljzq, mm.drdlcs, mm.ljdlcs, mm.drylcs, mm.ljylcs, mm.drzbgs, mm.ljzbgs, mm.drdzbsm, mm.ljdzbsm, mm.drxxpz, mm.ljxxpz,     "
				"  nvl(nn.drtjsj, 0) drtjsj, case when nvl(mm.drls,0)>=1 then nvl(nn.drzjzyl, 100) else nvl(nn.drzjzyl, 0) end drzjzyl,   "
				"  nvl(nn.ljtjsj, 0) ljtjsj, case when nvl(mm.ljls,0)>=1 then nvl(nn.ljzjzyl, 100) else nvl(nn.ljzjzyl, 0) end ljzjzyl     "
				"  from(     "
				"  select zjh, sum(drls) drls, sum(ljls) ljls, sum(drjzgsl) drjzgsl, sum(ljjzgsl) ljjzgsl,     "
				"  sum(drgpqgl) drgpqgl, sum(ljgpqgl) ljgpqgl, sum(drjzzzq) drjzzzq, sum(ljjzzzq) ljjzzzq,     "
				"  sum(drzq) drzq, sum(ljzq) ljzq, sum(drdlcs) drdlcs, sum(ljdlcs) ljdlcs, sum(drylcs) drylcs, sum(ljylcs) ljylcs, sum(drzbgs) drzbgs, sum(ljzbgs) ljzbgs,     "
				"  decode(sum(drzbgs), 0, 0, cast(sum(drzbls) / sum(drzbgs) as decimal(10, 1))) drdzbsm,     "
				"  decode(sum(ljzbgs), 0, 0, cast(sum(ljzbls) / sum(ljzbgs) as decimal(10, 1))) ljdzbsm,     "
				"  sum(drxxpz) drxxpz, sum(ljxxpz) ljxxpz     "
				"  from(     "
				"  select decode(substr(a.CAST_NO, 2, 1), '1', '4.1', '2', '4.1', '3', '4.1', '4', '4.1', '8') zjh, 0 as drls, 0 as drjzgsl, 0 as drgpqgl, 0 as drjzzzq, 0 as drzq,     "
				"  count(a.heat_no) as ljls, sum(a.CAST_STEEL_WT) as ljjzgsl, sum(b.slab_wt) as ljgpqgl,     "
				"  sum(a.POUR_PERIOD) ljjzzzq, cast(round(cast(sum(a.POUR_PERIOD) as decimal(31, 3)) / count(a.heat_no), 2) as decimal(31, 2)) ljzq,     "
				"  sum(decode(substr(a.cast_no, 2, 1), '5', 6 - CUTOFF_TIMES, '6', 6 - CUTOFF_TIMES, '7', 6 - CUTOFF_TIMES, 0)) drdlcs, 0 ljdlcs,     "
				"  0 drylcs, 0 ljylcs, 0 drzbgs, 0 ljzbgs, 0 drxxpz, 0 ljxxpz, 0 drzbls, 0 ljzbls     "
				"  from tmmsm31 a, (select heat_no, SUM(SLAB_WT) slab_wt FROM TMMSM33 group by heat_no) b     "
				"  WHERE a.OPEN_TIME<>' ' and a.heat_no = b.heat_no     "
				"  and a.OPEN_TIME >= @datetime1     "
				"  and a.OPEN_TIME <  @datetime2     "
				"  group by decode(substr(a.CAST_NO, 2, 1), '1', '4.1', '2', '4.1', '3', '4.1', '4', '4.1', '8')     "
				"  union all     "
				"  	select decode(substr(a.CAST_NO, 2, 1), '1', '4.1', '2', '4.1', '3', '4.1', '4', '4.1', '8') zjh, count(a.heat_no) drls, sum(a.CAST_STEEL_WT) drjzgsl, sum(b.slab_wt) drgpqgl,     "
				"  sum(a.POUR_PERIOD) drjzzzq, cast(round(cast(sum(a.POUR_PERIOD) as decimal(31, 3)) / count(a.heat_no), 2) as decimal(31, 2)) drzq,     "
				"  0 ljls, 0 as ljjzgsl, 0 as ljgpqgl, 0 as ljjzzzq, 0 as ljzq,     "
				"  0 drdlcs, sum(decode(substr(a.cast_no, 2, 1), '5', 6 - CUTOFF_TIMES, '6', 6 - CUTOFF_TIMES, '7', 6 - CUTOFF_TIMES, 0)) ljdlcs, 0 drylcs, 0 ljylcs,     "
				"  0 drzbgs, 0 ljzbgs, 0 drxxpz, 0 ljxxpz, 0 drzbls, 0 ljzbls     "
				"  from tmmsm31 a, (select heat_no, SUM(SLAB_WT) slab_wt FROM TMMSM33 group by heat_no) b     "
				"  WHERE a.OPEN_TIME<>' '	and a.heat_no = b.heat_no     "
				"  and TO_CHAR((to_date(a.OPEN_TIME, 'YYYYMMDDHH24MISS') + 3 HOUR), 'YYYYMMDD') = @v_date     "
				"  group by decode(substr(a.CAST_NO, 2, 1), '1', '4.1', '2', '4.1', '3', '4.1', '4', '4.1', '8')     "
				"  union all     "
				"	  select decode(substr(t.CAST_NO, 2, 1), '1', '4.1', '2', '4.1', '3', '4.1', '4', '4.1', '8') zjh,	 														"
				"					  0 drls, 0 drjzgsl, 0 drgpqgl, 0 drjzzzq, 0 drzq, 0 ljls, 0 as ljjzgsl, 0 as ljgpqgl, 0 as ljjzzzq, 0 as ljzq, 0 drdlcs, 0 ljdlcs, 0 drylcs, 0 ljylcs,	 										"
				"					  0, count(t.heat_no) ljzbgs, 0 drxxpz, 0 ljxxpz ,0 drzbls,sum(mid_heat_seq) ljzbls   from tmmsm31  t,	 										"
				"	          (select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq  from 															"
				"	                          (select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11	 														"
				"	                				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41	 										"
				"	                				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11b	 										"
				"	                				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41b	)										"
				"	          where (cast_no,mid_seq,mid_heat_seq) in 															"
				"	            				  (select cast_no,mid_seq,max(mid_heat_seq) from											"
				"	                        (select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11	 														"
				"	              				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41	 										"
				"	              				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11b	 										"
				"	              				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41b)											"
				"	                       where cast_no||lpad(mid_seq,2,0) not in 															"
				"	                       (select jcxx from (select substr(cast_no,2,1), max(cast_no||lpad(mid_seq,2,0)) jcxx from 															"
				"	                                                  (select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11	 														"
				"	                                          				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41	 										"
				"	                                          				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11b	 										"
				"	                                          				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41b)											"
				"	                                          group by substr(cast_no,2,1) )  )															"
				"	                      group by cast_no,mid_seq)   ) tp11	        														"
				"					  where t.heat_no = tp11.heat_no  											"
				"					    and close_time<>' '	 										"
				"					    and close_time>=@datetime1 											"
				"	            and close_time< @datetime2            															"
				"					 group by decode(substr(t.CAST_NO, 2, 1), '1', '4.1', '2', '4.1', '3', '4.1', '4', '4.1', '8') 											"
				"  union all     "
				"	 select decode(substr(t.CAST_NO, 2, 1), '1', '4.1', '2', '4.1', '3', '4.1', '4', '4.1', '8')  zjh,	 															"
				"					  0 drls, 0 drjzgsl, 0 drgpqgl, 0 drjzzzq, 0 drzq, 0 ljls, 0 as ljjzgsl, 0 as ljgpqgl, 0 as ljjzzzq, 0 as ljzq, 0 drdlcs, 0 ljdlcs, 0 drylcs, 0 ljylcs,	 											"
				"					  count(t.heat_no) drzbgs, 0 ljzbgs, 0 drxxpz, 0 ljxxpz , sum(mid_heat_seq) drzbls,0 ljzbls  from tmmsm31  t,	 	 										"
				"	          (select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq  from 																"
				"	                          (select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11	 															"
				"	                				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41	 											"
				"	                				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11b	 											"
				"	                				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41b	)											"
				"	          where (cast_no,mid_seq,mid_heat_seq) in 																"
				"	            				  (select cast_no,mid_seq,max(mid_heat_seq) from												"
				"	                        (select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11	 															"
				"	              				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41	 											"
				"	              				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11b	 											"
				"	              				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41b)												"
				"	                       where cast_no||lpad(mid_seq,2,0) not in 																"
				"	                       (select jcxx from (select substr(cast_no,2,1), max(cast_no||lpad(mid_seq,2,0)) jcxx from 																"
				"	                                                  (select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11	 															"
				"	                                          				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41	 											"
				"	                                          				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm11b	 											"
				"	                                          				  union all  select heat_no, cast_no, cast_div_no, mid_seq, mid_heat_seq from tpssm41b)												"
				"	                                          group by substr(cast_no,2,1) )  )																"
				"	                      group by cast_no,mid_seq)   ) tp11	        															"
				"					  where t.heat_no = tp11.heat_no  												"
				"					    and close_time<>' '	 											"
				"					    and TO_CHAR((to_date(close_time, 'YYYYMMDDHH24MISS') + 3 HOUR), 'YYYYMMDD') = @v_date	 											"
				"					 group by decode(substr(t.CAST_NO, 2, 1), '1', '4.1', '2', '4.1', '3', '4.1', '4', '4.1', '8')  												"
				"  union all     "
				"  select  decode(substr(mat_no, 9, 1), '1', '4.1', '2', '4.1', '3', '4.1', '4', '4.1', '5', '4.1', '8') zjh,     "
				"  0 drls, 0 drjzgsl, 0 drgpqgl, 0 drjzzzq, 0 drzq, 0 ljls, 0 as ljjzgsl, 0 as ljgpqgl, 0 as ljjzzzq, 0 as ljzq, 0 drdlcs, 0 ljdlcs, 0 drylcs, 0 ljylcs,     "
				"  0 drzbgs, 0 ljzbgs, decimal(SUM(MAT_WT), 20, 3) drxxpz, 0 ljxxpz, 0 drzbls, 0 ljzbls     "
				"  from twma4     "
				"  where STOCK_OPER_ORDER = '1B' and SLAT_UNLADE_CAUSE<>' '  and FUNC_ID='wmsmsm13_downline'     "
				"  and TO_CHAR((to_date(REC_CREATE_TIME, 'YYYYMMDDHH24MISS') + 3 HOUR), 'YYYYMMDD') = @v_date     "
				"  group by decode(substr(mat_no, 9, 1), '1', '4.1', '2', '4.1', '3', '4.1', '4', '4.1', '5', '4.1', '8')     "
				"  union all     "
				"  select  decode(substr(mat_no, 9, 1), '1', '4.1', '2', '4.1', '3', '4.1', '4', '4.1', '5', '4.1', '8') zjh,     "
				"  0 drls, 0 drjzgsl, 0 drgpqgl, 0 drjzzzq, 0 drzq, 0 ljls, 0 as ljjzgsl, 0 as ljgpqgl, 0 as ljjzzzq, 0 as ljzq, 0 drdlcs, 0 ljdlcs, 0 drylcs, 0 ljylcs,     "
				"  0 drzbgs, 0 ljzbgs, 0 drxxpz, decimal(SUM(MAT_WT), 20, 3) ljxxpz, 0 drzbls, 0 ljzbls     "
				"  from twma4     "
				"  where STOCK_OPER_ORDER = '1B' and SLAT_UNLADE_CAUSE<>' '  and FUNC_ID='wmsmsm13_downline'     "
				"  and REC_CREATE_TIME >= @datetime1     "
				"  and REC_CREATE_TIME <  @datetime2     "
				"  group by decode(substr(mat_no, 9, 1), '1', '4.1', '2', '4.1', '3', '4.1', '4', '4.1', '5', '4.1', '8')     "
				"  union all select '4.1' ZJH, 0 drls, 0 drjzgsl, 0 drgpqgl, 0 drjzzzq, 0 drzq, 0 ljls, 0 as ljjzgsl, 0 as ljgpqgl, 0 as ljjzzzq, 0 as ljzq, 0 drdlcs, 0 ljdlcs, 0 drylcs, 0 ljylcs,     "
				"  0 drzbgs, 0 ljzbgs, 0 drxxpz, 0 ljxxpz, 0 drzbls, 0 ljzbls  from SYSIBM.SYSDUMMY1     "
				"  union all select '8' ZJH, 0 drls, 0 drjzgsl, 0 drgpqgl, 0 drjzzzq, 0 drzq, 0 ljls, 0 as ljjzgsl, 0 as ljgpqgl, 0 as ljjzzzq, 0 as ljzq, 0 drdlcs, 0 ljdlcs, 0 drylcs, 0 ljylcs,     "
				"  0 drzbgs, 0 ljzbgs, 0 drxxpz, 0 ljxxpz, 0 drzbls, 0 ljzbls  from SYSIBM.SYSDUMMY1     "
				"  )     "
				"  group by zjh)  mm  left join     "
				"		(	select zjh, sum(drtjsj) drtjsj, sum(drzjzyl) drzjzyl, sum(ljtjsj) ljtjsj, sum(ljzjzyl) ljzjzyl from (	       																																						"
				"															  select  zjh,sum(tjsjjg) drtjsj, round(cast((1 - sum(tjsjjg)*1.0 / 1440.00/3 ) * 100 as decimal(6, 2)), 2) drzjzyl, 0 ljtjsj, 0 ljzjzyl from (																											"
				"															           select zjh,sum(tjsj) tjsjjg  from (																											"
				"															 select decode(zjh, '1', '4.1', '2', '4.1', '3', '4.1', '8') zjh,rq,sjc1 tjsj from (																											"
				"															  select substr(sjc.cast_no,2,1) zjh, to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq,																											"
				"															  right(digits(cast(timestampdiff(4,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),4) sjc1,																											"
				"															  right(digits(cast(timestampdiff(4,(to_date(to_char((to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR),'yyyymmdd')||'240000','yyyymmddhh24miss'))-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),4) sjc2,																											"
				"															  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq2,																											"
				"															  right(digits(cast(timestampdiff(4,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss')) as  bigint)),4) sjc3,																											"
				"															  to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR tjsj,to_date(to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'240000','yyyymmddhh24miss') tjrq1, 																											"
				"															  to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR kjsj,to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss') kjrq2, 																											"
				"															  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')-to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') sjc,																											"
				"															  *																											"
				"															  from 																											"
				"															  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3') and cast_div_no = '1') xjc,      																											"
				"															  					  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3')      																						"
				"															  					  and(substr(cast_no, 1, 6), cast_div_no) in      																						"
				"															  					  (select substr(cast_no, 1, 6), max(cast_div_no) from tmmsm31 group by substr(cast_no, 1, 6))) sjc      																						"
				"															  					   where substr(xjc.cast_no,2,5) = substr(sjc.cast_no,2,5) + 1    																						"
				"															              and sjc.CLOSE_TIME<>' ' and xjc.open_time<>' '																											"
				"															   order by xjc.CAST_NO desc ) where sjc=0 																											"
				"															 union all																											"
				"															  select decode(zjh, '1', '4.1', '2', '4.1', '3', '4.1', '8') zjh,rq,sjc2 from (																											"
				"															  select substr(sjc.cast_no,2,1) zjh, to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq,																											"
				"															  right(digits(cast(timestampdiff(4,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),4) sjc1,																											"
				"															  right(digits(cast(timestampdiff(4,(to_date(to_char((to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR),'yyyymmdd')||'240000','yyyymmddhh24miss'))-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),4) sjc2,																											"
				"															  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq2,																											"
				"															  right(digits(cast(timestampdiff(4,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss')) as  bigint)),4) sjc3,																											"
				"															  to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR tjsj,to_date(to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'240000','yyyymmddhh24miss') tjrq1, 																											"
				"															  to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR kjsj,to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss') kjrq2, 																											"
				"															  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')-to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') sjc,																											"
				"															  *																											"
				"															  from 																											"
				"															  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3') and cast_div_no = '1') xjc,      																											"
				"															  					  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3')      																						"
				"															  					  and(substr(cast_no, 1, 6), cast_div_no) in      																						"
				"															  					  (select substr(cast_no, 1, 6), max(cast_div_no) from tmmsm31 group by substr(cast_no, 1, 6))) sjc      																						"
				"															  					   where substr(xjc.cast_no,2,5) = substr(sjc.cast_no,2,5) + 1  																						"
				"															              and sjc.CLOSE_TIME<>' ' and xjc.open_time<>' '																											"
				"															   order by xjc.CAST_NO desc ) where sjc=1																											"
				"															   union all																											"
				"															  select decode(zjh, '1', '4.1', '2', '4.1', '3', '4.1', '8') zjh,rq2,sjc3 from (																											"
				"															  select substr(sjc.cast_no,2,1) zjh, to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq,																											"
				"															  right(digits(cast(timestampdiff(4,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),4) sjc1,																											"
				"															  right(digits(cast(timestampdiff(4,(to_date(to_char((to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR),'yyyymmdd')||'240000','yyyymmddhh24miss'))-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),4) sjc2,																											"
				"															  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq2,																											"
				"															  right(digits(cast(timestampdiff(4,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss')) as  bigint)),4) sjc3,																											"
				"															  to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR tjsj,to_date(to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'240000','yyyymmddhh24miss') tjrq1, 																											"
				"															  to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR kjsj,to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss') kjrq2, 																											"
				"															  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')-to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') sjc,																											"
				"															  *																											"
				"															  from 																											"
				"															  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3') and cast_div_no = '1') xjc,      																											"
				"															  					  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3')      																						"
				"															  					  and(substr(cast_no, 1, 6), cast_div_no) in      																						"
				"															  					  (select substr(cast_no, 1, 6), max(cast_div_no) from tmmsm31 group by substr(cast_no, 1, 6))) sjc      																						"
				"															  					  where substr(xjc.cast_no,2,5) = substr(sjc.cast_no,2,5) + 1     																						"
				"															              and sjc.CLOSE_TIME<>' ' and xjc.open_time<>' '																											"
				"															   order by xjc.CAST_NO desc ) where sjc=1 																											"
				"															   )																											"
				"															   where rq=@v_date																											"
				"															   group by zjh,rq																											"
				"															  																											"
				"															 ) group by zjh																											"
				"															 																											"
				"															 union all																											"
				"															 																											"
				"															 select zjh, 0 drtjsj, 0 drzjzyl, cast(sum(tjsjjg)/60 as decimal(20,0)) ljtjsj, cast(100 * (1 - sum(tjsjjg)/60*1.0 / timestampdiff(16, to_date(substr(@datetime2, 1, 8), 'yyyymmdd') - to_date(substr(@datetime1, 1, 8), 'yyyymmdd')) / 1440 / 3 ) as decimal(20, 2))  ljzjzyl from (																											"
				"															           select  zjh,sum(tjsj) tjsjjg  from (																											"
				"															 select decode(zjh, '1', '4.1', '2', '4.1', '3', '4.1', '8') zjh,rq,sjc1 tjsj from (																											"
				"															  select substr(sjc.cast_no,2,1) zjh, to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq,																											"
				"															  right(digits(cast(timestampdiff(2,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),8) sjc1,																											"
				"															  right(digits(cast(timestampdiff(2,(to_date(to_char((to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR),'yyyymmdd')||'240000','yyyymmddhh24miss'))-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),8) sjc2,																											"
				"															  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq2,																											"
				"															  right(digits(cast(timestampdiff(2,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss')) as  bigint)),8) sjc3,																											"
				"															  to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR tjsj,to_date(to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'240000','yyyymmddhh24miss') tjrq1, 																											"
				"															  to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR kjsj,to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss') kjrq2, 																											"
				"															  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')-to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') sjc,																											"
				"															  *																											"
				"															  from 																											"
				"															  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3') and cast_div_no = '1') xjc,      																											"
				"															  					  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3')      																						"
				"															  					  and(substr(cast_no, 1, 6), cast_div_no) in      																						"
				"															  					  (select substr(cast_no, 1, 6), max(cast_div_no) from tmmsm31 group by substr(cast_no, 1, 6))) sjc      																						"
				"															  					    where substr(xjc.cast_no,2,5) = substr(sjc.cast_no,2,5) + 1    																						"
				"															              and sjc.CLOSE_TIME<>' ' and xjc.open_time<>' '																											"
				"															   order by xjc.CAST_NO desc ) where sjc=0 																											"
				"															 union all																											"
				"															  select decode(zjh, '1', '4.1', '2', '4.1', '3', '4.1', '8') zjh,rq,sjc2 from (																											"
				"															  select substr(sjc.cast_no,2,1) zjh, to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq,																											"
				"															  right(digits(cast(timestampdiff(2,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),8) sjc1,																											"
				"															  right(digits(cast(timestampdiff(2,(to_date(to_char((to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR),'yyyymmdd')||'240000','yyyymmddhh24miss'))-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),8) sjc2,																											"
				"															  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq2,																											"
				"															  right(digits(cast(timestampdiff(2,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss')) as  bigint)),8) sjc3,																											"
				"															  to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR tjsj,to_date(to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'240000','yyyymmddhh24miss') tjrq1, 																											"
				"															  to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR kjsj,to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss') kjrq2, 																											"
				"															  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')-to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') sjc,																											"
				"															  *																											"
				"															  from 																											"
				"															  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3') and cast_div_no = '1') xjc,      																											"
				"															  					  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3')      																						"
				"															  					  and(substr(cast_no, 1, 6), cast_div_no) in      																						"
				"															  					  (select substr(cast_no, 1, 6), max(cast_div_no) from tmmsm31 group by substr(cast_no, 1, 6))) sjc      																						"
				"															  					   where substr(xjc.cast_no,2,5) = substr(sjc.cast_no,2,5) + 1   																						"
				"															              and sjc.CLOSE_TIME<>' ' and xjc.open_time<>' '																											"
				"															   order by xjc.CAST_NO desc ) where sjc=1																											"
				"															   union all																											"
				"															  select decode(zjh, '1', '4.1', '2', '4.1', '3', '4.1', '8') zjh,rq2,sjc3 from (																											"
				"															  select substr(sjc.cast_no,2,1) zjh, to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq,																											"
				"															  right(digits(cast(timestampdiff(2,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),8) sjc1,																											"
				"															  right(digits(cast(timestampdiff(2,(to_date(to_char((to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR),'yyyymmdd')||'240000','yyyymmddhh24miss'))-(to_date(sjc.CLOSE_TIME,'yyyymmddhh24miss') + 3 HOUR)) as  bigint)),8) sjc2,																											"
				"															  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') rq2,																											"
				"															  right(digits(cast(timestampdiff(2,(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR)-to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss')) as  bigint)),8) sjc3,																											"
				"															  to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR tjsj,to_date(to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'240000','yyyymmddhh24miss') tjrq1, 																											"
				"															  to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR kjsj,to_date(to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')||'000000','yyyymmddhh24miss') kjrq2, 																											"
				"															  to_char(to_date(xjc.open_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd')-to_char(to_date(sjc.close_time,'yyyymmddhh24miss') + 3 HOUR,'yyyymmdd') sjc,																											"
				"															  *																											"
				"															  from 																											"
				"															  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3') and cast_div_no = '1') xjc,      																											"
				"															  					  (select substr(cast_no, 1, 6) cast_no, cast_div_no, open_time, close_time from tmmsm31  where substr(cast_no, 2, 1) in('1', '2', '3')      																						"
				"															  					  and(substr(cast_no, 1, 6), cast_div_no) in      																						"
				"															  					  (select substr(cast_no, 1, 6), max(cast_div_no) from tmmsm31 group by substr(cast_no, 1, 6))) sjc      																						"
				"															  					    where substr(xjc.cast_no,2,5) = substr(sjc.cast_no,2,5) + 1  																						"
				"															              and sjc.CLOSE_TIME<>' ' and xjc.open_time<>' '																											"
				"															   order by xjc.CAST_NO desc ) where sjc=1 																											"
				"															   )																											"
				"															   where rq>=@datetime1																											"
				"															     and rq< @datetime2																											"
				"															   group by zjh																											"
				"															  																											"
				"															 ) group by zjh																											"
				"															 )  group by zjh																											"

				" )  nn	on  mm.zjh = nn.zjh        "
				"  ) where xh < 5 order by xh  ";




			break;
		}
		Log::Trace("", __FUNCTION__, "sqlstr				= [{0}]", (const char*)sqlstr);

		cmd_inq.Parameters.Clear();
		cmd_inq.Parameters.Set("datetime1", datetime1);
		cmd_inq.Parameters.Set("datetime2", datetime2);
		cmd_inq.Parameters.Set("v_date", v_date);
		cmd_inq.SetCommandText(sqlstr);
		cmd_inq.ExecuteQuery(bcls_ret->Tables[0]);
		cmd_inq.Close();

	}
	catch (CDbException& ex)					//捕获数据库操作异常
	{
		CFormattable arguments[] = { ex.GetCode() };
		CMessageFormat::Format(s.msg, _RES("GCRSS0000021")/*信息读取失败。*/, arguments, 1);
		CString str = sqlstr + "\r\n" + ex.GetMsg();
		strncpy(s.sysmsg, (const char*)str, sizeof(s.sysmsg) - 1);
		s.flag = -1;
		doFlag = -1; //数据库异常时返回-1，事务将被回滚
	}
	catch (const CApplicationException& ex)	//捕获应用错误
	{
		s.flag = ex.GetCode();
		doFlag = -1;
	}
	catch (CException& ex)
	{
		strncpy(s.msg, (const char*)ex.GetMsg(), sizeof(s.msg) - 1);
		s.flag = ex.GetCode();
		doFlag = -1;
	}

	return(doFlag);
}